### ISSUE TITLE
Support node esm proposal which mixed .js and .mjs files

### ISSUE THREAD

**Issue by dinoboff** [sindresorhus/xo#258]
A use case is standard-things/esm where most file are authored in ES modules with a few script to bridge with node's `require`.

With eslint 4.1+, it would be the equivalent of `eslint --ext js,mjs` with:
```yaml
# .eslintrc.yml
extends:
  - xo/esnext
parserOptions:
  sourceType: script
overrides:
  - files: ['**/*.mjs']
    parserOptions:
      sourceType: module
```
